#  wall_watcher_dd_wrt_log_reader.py

import sys


def decode_line(line):
    # split log line
    # Generated by wallwatcher for dd-wrt
    #  its tab serpartated
    line_data = line.split('\t')
    line_dict = {}
    line_dict['date'] = line_data.pop(0)
    line_dict['time'] = line_data.pop(0)
    line_dict['code'] = line_data.pop(0)
    line_dict['protocol'] = line_data.pop(0)
    line_dict['remote_ip'] = line_data.pop(0)
    line_dict['remote_domain'] = line_data.pop(0)
    line_dict['remote_port'] = line_data.pop(0)
    line_dict['local_ip'] = line_data.pop(0)
    line_dict['local_port'] = line_data.pop(0)

    return line_dict

def lastest(a):
    return a[-1]


def main():
    # figure out which files to read
    # load files data smartly into a dictionary

    filename = sys.argv[1]
    domains = dict()
    f = open(filename, 'r')
    lines = f.readlines()
    f.close()

    for line in lines:
        entry = decode_line(line)

        if entry['protocol'] == 'udp':
            if entry['remote_ip'] in domains.keys():
                domains[entry['remote_ip']] += 1
            else:
                domains[entry['remote_ip']] = 1

    print '\nLines in log:', len(lines), 'domains used:', len(domains)

    #build a list of top domains
    top_domains = []
    for a in domains.keys():
        top_domains.append((a, domains[a]))

    top_domains = sorted(top_domains, key=lastest, reverse=True)

    for n in range(min(10, len(domains))):
        a, b = top_domains.pop(0)
        print('Rank:' + str(n + 1)  + ' Addr: ' + str(a) +' hits:' +
            str(b))



if __name__ == '__main__':
    main()